#version: '3'
#
#services:
#  kafka-producer-consumer-test:
#    image: play-kafka-0.0.1-SNAPSHOT
#    hostname: kafka-producer-consumer-test
#    container_name: kafka-producer-consumer-test
#    ports:
#    - 8080:8080
#    environment:
#      HUMAN_LOG_FILE_LOCATION: /var/log/kafka/play-kafka/kafka.log
#    volumes:
#      - /var/log/kafka/play-kafka:/var/log/kafka/play-kafka


version: "3"

services:
  kafka-producer-test:
    image: play-kafka:0.0.1-SNAPSHOT
    hostname: kafka-producer-test
    container_name: kafka-producer-test
    ports:
      - "8080:8080"
    environment:
#      SPRING_PROFILES_ACTIVE: producer,local spring.kafka.consumer.bootstrap-servers
      KAFKA_BOOTSTRAP_ADDRESS: http://kafka-1:19091
      KAFKA_SCHEMA_REGISTRY_ADDRESS: http://schema-registry:8081
      KAFKA_PRODUCER_ACKS: 1
      KAFKA_PRODUCER_BATCH_SIZE_IN_BYTES: 16000
      KAFKA_PRODUCER_LINGER_MS: 5
      KAFKA_PRODUCER_COMPRESSION_TYPE: none
      HUMAN_LOG_FILE_LOCATION: /var/log/kafka/play-kafka/kafka-producer.log
#      GELF_LOG_FILE_LOCATION: /var/log/kafka/kafka-test/producer-gelf-kafka-test.log
    volumes:
      - /var/log/kafka/kafka-test:/var/log/kafka/kafka-test

  kafka-consumer-test:
    image: play-kafka:0.0.1-SNAPSHOT
    hostname: kafka-consumer-test
    container_name: kafka-consumer-test
    ports:
      - "8082:8080"
    environment:
#      SPRING_PROFILES_ACTIVE: consumer,local
      KAFKA_BOOTSTRAP_ADDRESS: http://kafka-1:19091
      KAFKA_SCHEMA_REGISTRY_ADDRESS: http://schema-registry:8081
      KAFKA_CONSUMER_GROUP_ID: group_id
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: latest
      KAFKA_CONSUMER_FETCH_MIN_BYTES: 1
      KAFKA_CONSUMER_FETCH_MAX_WAIT_MS: 1
      HUMAN_LOG_FILE_LOCATION: /var/log/kafka/play-kafka/kafka-consumer.log
#      GELF_LOG_FILE_LOCATION: /var/log/kafka/kafka-test/consumer-gelf-kafka-test.log
    volumes:
      - /var/log/kafka/kafka-test:/var/log/kafka/kafka-test


